In [1]:
#INMAS Worksop4: Group A: Simulating fulfillment center
# @c: Ben, Issac, Sultan, Vlassis, Yantao
# for 1<=i<=M, the i-th order has length n_i = sum_j n_ij where n_ij means the number of product j in i-th order (1<=j<=N).
# we consider the following setup: (for any i) n_ij ~ Geom(1/(1+|w_j|))-1 where w_j ~ N(0,1). Here we assume n_ij are independent in i


In [66]:
import numpy as np
N = 10
M = 5
omega = np.random.normal(0, 1, N)
omega = abs(omega)
nij   = np.random.geometric(p=1/(1+omega) ,size=(M,N)) -1
print(omega)
print(nij)

[0.09202473 0.78257594 1.2312475  1.64979971 0.40424411 1.39848216
 0.6905179  0.12272271 0.44964487 0.51346153]
[[0 1 0 2 1 0 1 0 1 0]
 [0 0 1 6 0 3 0 0 0 0]
 [0 0 0 1 0 1 2 0 2 0]
 [0 5 4 1 0 1 1 0 0 1]
 [1 1 0 2 1 1 1 0 0 0]]


In [67]:
orderbook = []
for i in range(M): 
    orderbook.append(np.concatenate([[j]*nij[i,j] for j in range(N)]))
orderbook

[array([1., 3., 3., 4., 6., 8.]),
 array([2., 3., 3., 3., 3., 3., 3., 5., 5., 5.]),
 array([3., 5., 6., 6., 8., 8.]),
 array([1., 1., 1., 1., 1., 2., 2., 2., 2., 3., 5., 6., 9.]),
 array([0., 1., 3., 3., 4., 5., 6.])]